function plotdata(data)
% signal: struct generated by jsonbuild, contains all info in the json file
    disp(['plotting ','...'])
    figure
    hold on
    N=20;
    
    for i=1:length(data.traces{1,1}{1,6}.values)
        ts = data.traces{1,1}{1,5}.values{i}.time;
        it = data.traces{1,1}{1,5}.values{i}.enclosure;
        w = ts(2) - ts(1);
        h = it(2) - it(1);
        
        if w==0
            hv = it(1):h/N:it(1);
            plot(ts(1)*ones(1,length(hv)), hv,'r')
            hold on
            
        elseif h==0
            wv = ts(1):w/N:ts(2);
            plot(wv, it(1)*ones(1,length(wv)),'r')
            hold on
            
        else
            
            rectangle('position', [ts(1),it(1), w,h], 'facecolor', 'b')
            
            hold on
            
        end
        
    end
    title(sn)
    
end